/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms. */

package main

import "fmt"

func main() {
	// Initialize the variables of Fibonacci sequence
	var i, j, k int = 1, 2, 0

	// Initialize sum to accumulate multiples of even values of Fibonacci sequence
	var sum int = 2

	// Loop through numbers from 0 to 399999
	for k < 4000000 {
		k = i + j
		i = j
		j = k

		// If k is even add to sum
		if k%2 == 0 {
			sum += k
		}

	}

	// Print the computed sum.
	fmt.Println("Soma:", sum)
}
